### ISSUE TITLE
Unable to open the Tool in latest PKHeX release

### ISSUE THREAD

**Issue by QuinnWasTaken** [Bl4ckSh4rk/PKHeXFeebasLocatorPlugin#10]
I get an exception upon trying to use the plugin in PKHeX, Attached is the exception details
[Exception.txt](https://github.com/Bl4ckSh4rk/PKHeXFeebasLocatorPlugin/files/11185630/Exception.txt)

**Comment by Bl4ckSh4rk** [comment]
Thanks, fixed in fd27399.
