### ISSUE TITLE
Option "Greyed out" in PKHeX

### ISSUE THREAD

**Issue by Addison0ne** [Bl4ckSh4rk/PKHeXFeebasLocatorPlugin#4]
Hi The option for this plugin under tools is greyed out for my pokemon diamond save file.
I've tried different versions of PKHeX to no avail.
![Screenshot 2022-01-17 121912](https://user-images.githubusercontent.com/52065774/149690801-8e5e3c4d-b2ab-4201-ab68-14ee134121a1.png)

**Comment by Bl4ckSh4rk** [comment]
Should be fixed with the latest commit b74406ab22d45386ad232908ed3091b348e3d722
~~I'm uploading the compiled plugin later.~~

Get the latest release of the plugin and make sure to update PKHeX as well.
https://projectpokemon.org/home/files/file/2885-pkhex-plugin-feebas-locator/

**Comment by Selim042** [comment]
Its grayed out for me too on Ruby
![image](https://user-images.githubusercontent.com/8419844/162639903-f8d49d03-b66f-464a-ae5e-3d4181729230.png)

**Comment by Addison0ne** [comment]
> Its grayed out for me too on Ruby
> 
> ![image](https://user-images.githubusercontent.com/8419844/162639903-f8d49d03-b66f-464a-ae5e-3d4181729230.png)
> 
> 

I just used it for ruby yesterday and it worked fine have you made sure both pkhex and the plug-in are up to date?

**Comment by Selim042** [comment]
I just downloaded the plugin minutes before posting this, and PKHeX is on latest.

**Comment by Addison0ne** [comment]
> I just downloaded the plugin minutes before posting this, and PKHeX is on latest.

![image](https://user-images.githubusercontent.com/52065774/162646678-714c5229-8066-4476-845c-c58ca11ed096.png)
I just tried it and it seems to work fine. If you want I could send you a copy of the plug-in that's working for me?

**Comment by Selim042** [comment]
I have PKHeX as the default operation when double clicking .sav files, it seems loading that way doesn't allow the plugin to work, but if I open the save when PKHeX is already open it works fine.
